---
title: "goodman_assignment05"
output: html_document
---

# First step... generate a matrix, size 50x50, and fill it randomly with values 1-4 to represent C, S, R, and empty spaces in the vector.

create.matrix <- function(variable, nrows=50,ncols=50){
	matrix(sample(variable, nrows*ncols, replace=TRUE), nrow=nrows, ncol=ncols)
}


# Pick random cell, sample surroundings, figure out what the cell will become

local.simulation <- function(matrix){
nrow <- sample(1:nrow(matrix), 1)
ncol <- sample(1:ncol(matrix), 1)
index <- c(nrow,ncol)
index.value <- matrix[nrow,ncol]

if(nrow==1 && ncol==1){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol+1]
c <- matrix[nrow(matrix),ncol(matrix)]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol(matrix)]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(nrow==1 && ncol==ncol(matrix)){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol(matrix)]
c <- matrix[nrow(matrix),ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol(matrix)]
g <- matrix[nrow, ncol(matrix)]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix) && ncol==ncol(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[1, ncol]
e <- matrix[1, ncol-1]
f <- matrix[1, 1]
g <- matrix[nrow, 1]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix) && ncol==1){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol(matrix)]
c <- matrix[nrow-1,ncol+1]
d <- matrix[1, ncol]
e <- matrix[1, ncol(matrix)]
f <- matrix[1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(nrow==1){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol+1]
c <- matrix[nrow(matrix),ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1]
} else if(ncol==1){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol(matrix)]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol(matrix)]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(ncol==ncol(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, 1]
g <- matrix[nrow, 1]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[1, ncol]
e <- matrix[1, ncol-1]
f <- matrix[1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1] 
} else {
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1] }
local <- c(a,b,c,d,e,f,g,h) 

deltaS0 <- 1/4
deltaR <- 10/32
deltaC <- 1/3
tau <- 3/4

if(index.value=="R"){
    index.value <- sample(c("R", "E"), 1, prob=c(1-deltaR, deltaR))
} else if(index.value=="C"){
    index.value <- sample(c("C", "E"), 1, prob=c(1-deltaC, deltaC))
} else if(index.value=="S"){
    present <- sum(local=="C")
    present <- present/8
    deltaS <- deltaS0 + tau*present
    index.value <- sample(c("S", "E"), 1, prob=c(1-deltaS, deltaS))
} else {
    index.value <- local[sample(1:8, 1)]
}
matrix[nrow,ncol] <<- index.value
}

abundance <- 1
for(i in 1:1000){
replicate(2500, local.simulation(matrix))
column <- rbind(1, sum(matrix=="R"), sum(matrix=="S"), sum(matrix=="C"))
abundance <- cbind(abundance, column)
}

abundance <- abundance[,-1]
abundance[1,1:1000] <- 1:1000
abundance[2,] <- sapply(abundance[2,], log10)
abundance[3,] <- sapply(abundance[3,], log10)
abundance[4,] <- sapply(abundance[4,], log10)
plot(abundance[1,], abundance[2,], type="l", col="green", ylim=c(0,5), ylab="Log (Abundance)", xlab="Time", main="Local Neighborhood")
lines(abundance[1,], abundance[3,], type="l", col="blue")
lines(abundance[1,], abundance[4,], type="l", col="red")
legend(x=0,y=1.5, c("R","S","C"), lty=c(1,1), lwd=c(2.5,2.5),col=c("green","blue","red"),cex=0.7)

global.simulation <- function(matrix){
nrow <- sample(1:nrow(matrix), 1)
ncol <- sample(1:ncol(matrix), 1)
index <- c(nrow,ncol)
index.value <- matrix[nrow,ncol]

deltaS0 <- 1/4
deltaR <- 10/32
deltaC <- 1/3
tau <- 3/4

if(index.value=="R"){
    index.value <- sample(c("R", "E"), 1, prob=c(1-deltaR, deltaR))
} else if(index.value=="C"){
    index.value <- sample(c("C", "E"), 1, prob=c(1-deltaC, deltaC))
} else if(index.value=="S"){
    present <- sum(matrix=="C")
    present <- present/2500
    deltaS <- deltaS0 + tau*present
    index.value <- sample(c("S", "E"), 1, prob=c(1-deltaS, deltaS))
} else {
    index.value <- sample(matrix, 1)
}
matrix[nrow,ncol] <<- index.value
}

abundance <- 1
for(i in 1:500){
replicate(2500, global.simulation(matrix))
column <- rbind(1, sum(matrix=="R"), sum(matrix=="S"), sum(matrix=="C"))
abundance <- cbind(abundance, column)
}

abundance <- abundance[,-1]
abundance[1,1:500] <- 1:500
abundance[2,] <- sapply(abundance[2,], log10)
abundance[3,] <- sapply(abundance[3,], log10)
abundance[4,] <- sapply(abundance[4,], log10)
plot(abundance[1,], abundance[2,], type="l", col="green", xlim=c(0,300), ylim=c(0,5), ylab="Log (Abundance)", xlab="Time", main="Global Neighborhood")
lines(abundance[1,], abundance[3,], type="l", col="blue")
lines(abundance[1,], abundance[4,], type="l", col="red")
legend(x=0,y=5, c("R","S","C"), lty=c(1,1), lwd=c(2.5,2.5),col=c("green","blue","red"),cex=0.7)