---
title: "goodman_assignment05 extra credit"
output: html_document
---

variable <- c("S", "R", "C", "E")
variable.num <- c(1,2,3,4)
create.matrix <- function(variable, nrows=50,ncols=50){
	matrix(sample(variable, nrows*ncols, replace=TRUE), nrow=nrows, ncol=ncols)
}
matrix <- create.matrix(variable.num)

local.simulation <- function(matrix){
nrow <- sample(1:nrow(matrix), 1)
ncol <- sample(1:ncol(matrix), 1)
index <- c(nrow,ncol)
index.value <- matrix[nrow,ncol]

if(nrow==1 && ncol==1){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol+1]
c <- matrix[nrow(matrix),ncol(matrix)]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol(matrix)]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(nrow==1 && ncol==ncol(matrix)){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol(matrix)]
c <- matrix[nrow(matrix),ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol(matrix)]
g <- matrix[nrow, ncol(matrix)]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix) && ncol==ncol(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[1, ncol]
e <- matrix[1, ncol-1]
f <- matrix[1, 1]
g <- matrix[nrow, 1]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix) && ncol==1){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol(matrix)]
c <- matrix[nrow-1,ncol+1]
d <- matrix[1, ncol]
e <- matrix[1, ncol(matrix)]
f <- matrix[1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(nrow==1){
a <- matrix[nrow(matrix),ncol]
b <- matrix[nrow(matrix),ncol+1]
c <- matrix[nrow(matrix),ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1]
} else if(ncol==1){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol(matrix)]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol(matrix)]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol(matrix)]
} else if(ncol==ncol(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, 1]
g <- matrix[nrow, 1]
h <- matrix[nrow, ncol-1]
} else if(nrow==nrow(matrix)){
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[1, ncol]
e <- matrix[1, ncol-1]
f <- matrix[1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1] 
} else {
a <- matrix[nrow-1,ncol]
b <- matrix[nrow-1,ncol+1]
c <- matrix[nrow-1,ncol-1]
d <- matrix[nrow+1, ncol]
e <- matrix[nrow+1, ncol-1]
f <- matrix[nrow+1, ncol+1]
g <- matrix[nrow, ncol+1]
h <- matrix[nrow, ncol-1] }
local <- c(a,b,c,d,e,f,g,h) 

deltaS0 <- 1/4
deltaR <- 10/32
deltaC <- 1/3
tau <- 3/4

if(index.value=="R"){
    index.value <- sample(c("R", "E"), 1, prob=c(1-deltaR, deltaR))
} else if(index.value=="C"){
    index.value <- sample(c("C", "E"), 1, prob=c(1-deltaC, deltaC))
} else if(index.value=="S"){
    present <- sum(local=="C")
    present <- present/8
    deltaS <- deltaS0 + tau*present
    index.value <- sample(c("S", "E"), 1, prob=c(1-deltaS, deltaS))
} else {
    index.value <- local[sample(1:8, 1)]
}
matrix[nrow,ncol] <<- index.value
}

heatmap(matrix, Rowv=NA,Colv=NA, col=c("blue","green","red","white"), labCol=NA, labRow=NA)

for(i in 1:5){
replicate(2500, local.simulation(matrix))
heatmap(matrix, Rowv=NA,Colv=NA, col=c("blue","green","red","white"), labCol=NA, labRow=NA)
}

png(file="example%02d.png", width=200, height=200)
  for (i in 1:5){
    replicate(2500, local.simulation(matrix))
    heatmap(matrix, Rowv=NA,Colv=NA, col=c("blue","green","red","white"),    labCol=NA, labRow=NA)
  }
dev.off()

# convert the .png files to one .gif file using ImageMagick. 
# The system() function executes the command as if it was done
# in the terminal. the -delay flag sets the time between showing
# the frames, i.e. the speed of the animation.
system("convert -delay 80 *.png example_1.gif")
# remove png files
file.remove(list.files(pattern=".png"))

